In [20]:
import numpy as np
from numpy import random

In [15]:
a=np.array([10,20,30])
print(a)
print(type(a))
print("version = ",np.__version__)

[10 20 30]
<class 'numpy.ndarray'>
version =  2.0.1


In [11]:
print(np.array(2))

2


In [18]:
b=np.array([10,20])
c=np.array([[1,2.1],[3,4]])
d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("1D array= \n",b)
print("Type= ",type(b))
print("2D array= \n",c)
print("Type= ",type(c))
print("3D array= \n",d)
print("Type= ",type(d))

1D array= 
 [10 20]
Type=  <class 'numpy.ndarray'>
2D array= 
 [[1.  2.1]
 [3.  4. ]]
Type=  <class 'numpy.ndarray'>
3D array= 
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Type=  <class 'numpy.ndarray'>


In [36]:
#attributes
#ndim,shape,size,dtype,itemsize
#Statistical Function
#max,miin,mean,median,sum,var,std
print(a.ndim)
#shape
print(d.shape)
#size
print(d.size)
#dtype
print(d.dtype)
#itemsize
print(d.itemsize)

1
(3, 3)
9
int64
8


In [17]:
#Sorting
e=np.array([3,2,50,25,13])
e.sort()
print(e)
f=np.sort(e)
print(f)
print(np.argsort(e))

[ 2  3 13 25 50]
[ 2  3 13 25 50]
[0 1 2 3 4]


In [37]:
#What,Why,application
#Advantages over python array
#Attributes
#Statistical Functions
#Slicing
#Type
#data Types
#create array
#Sorting

In [4]:
#Broadcasting...
g=np.ndarray([1,2,3])
h=np.ndarray([[1],[2],[3]])
print(np.add(g,h))

NameError: name 'np' is not defined

In [19]:
i=np.array([1,2,3,4])
j=np.array([1,2,3])
print(i+j)

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [22]:
#Random array generation
x=random.rand(100)
random.randint(100)
randint(100,size(5))
randint(100,size(3,5))
rand(5)
rand(3,5)
random.choice([3,5,7,9])
random.choice([3,5,7,9],size=(3,5))

NameError: name 'randint' is not defined

In [ ]:
# Ability of numpy to perform arithematic operation between arrays of different shapes is called broadcating.
# The shape should be compatible.
# Smaller array is broadcast across the larger array so that they have compatible shapes.