In [1]:
import numpy as np
from numpy import random

In [5]:
x=random.randint(100)
x=random.rand(100)
x=random.randint(100,size=(5))
x=random.randint(100,size=(3,5))
x=random.rand(5)
#x=rand(3,5)
x=random.choice([7,8,9,10,11])
y=random.choice(x,size=(3,5))
print(x,y)

8 [[3 7 3 2 6]
 [5 1 5 2 3]
 [0 6 0 7 0]]


In [8]:
a1=[[10,20,30,40],[50,60,70,80],[1,2,3,4]]
a2=[10,10,10,10]
print("add= ",np.add(a1,a2))
print("multiply= ",np.multiply(a1,a2))
print("subtract= ",np.subtract(a1,a2))
print("Divide= ",np.divide(a1,a2))
print("Divmod= ",np.divmod(a1,a2))
print("Mod= ",np.mod(a1,a2))
print("Remainder= ",np.remainder(a1,a2))
print("Power= ",np.power(a2,2))

add=  [[20 30 40 50]
 [60 70 80 90]
 [11 12 13 14]]
multiply=  [[100 200 300 400]
 [500 600 700 800]
 [ 10  20  30  40]]
subtract=  [[ 0 10 20 30]
 [40 50 60 70]
 [-9 -8 -7 -6]]
Divide=  [[1.  2.  3.  4. ]
 [5.  6.  7.  8. ]
 [0.1 0.2 0.3 0.4]]
Divmod=  (array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [0, 0, 0, 0]]), array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 2, 3, 4]]))
Mod=  [[0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]
Remainder=  [[0 0 0 0]
 [0 0 0 0]
 [1 2 3 4]]
Power=  [100 100 100 100]
